services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-ce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}

    #faltan usuario y contraseña
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: cms #creates the DB upon container initialization. Optional tho and replaceable by an SQL instrucction such as CREATE DATABASE in the sample SQL data file
      MYSQL_ROOT_PASSWORD: ${MY_SQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  mongodb_data: