services:

  mongodb:
    #debug image: mongodb/mongodb-community-server:latest
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./.env
    #environment:  - debug - not needed if env_file property works properly
      #- MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD} - debug - not needed if env_file property works properly #remember to leave no space after the "equal" as it is trated literally
      #- MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER} - debug - not needed if env_file property works properly #remember to leave no space after the "equal" as it is trated literally


  mysql:
    image: mysql:latest
    container_name: mysqldb
    env_file:
      - ./.env
    #environment: - debug - not needed if env_file property works properly
      #MYSQL_DATABASE: cms - debug - not needed if env_file property works properly #creates the DB upon container initialization. Optional tho and replaceable by an SQL instrucction such as CREATE DATABASE in the sample SQL data file
      #MYSQL_ROOT_PASSWORD: ${MY_SQL_PASSWORD} - debug - not needed if env_file property works properly
    ports:
      - "3307:3306" #3307 to avoid port conflict (happened to mine using Ubuntu and starting MySQL and Mongo using Docker manually)
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  mongodb_data: